name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like to see
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this feature? What problem does it solve?
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: Helps us understand your setup
      options:
        - Home Assistant Add-on
        - Docker Standalone
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered (optional)
      description: Have you considered any workarounds or alternative solutions?
